# By automating installs with an ansible role,
# you don't see the normal click-through from the website.
- name: GOOGLE CHROME AND THIRD PARTY TERMS OF SERVICE APPLY
  debug:
    msg: https://www.google.com/chrome/ or read
         https://www.google.com/intl/en/chrome/browser/privacy/eula_text.html

- name: Copy Google signing keys for Linux packages
  #
  # See https://www.google.com/linuxrepositories/
  copy:
    src: "{{ item }}"
    dest: /ansible-managed/google-chrome/
  with_items:
    - linux_signing_key.pub
    - key_fingerprints.txt

- name: Copy script for checking key fingerprints
  # Ansible copy module does not preserve executable bit, unlike `cp`.
  copy:
    src: "{{ item }}"
    dest: /ansible-managed/google-chrome/
    mode: a+x
  with_items:
    - keyfile_to_fingerprints.sh

- name: Install GPG for checking key fingerprints
  package: name=gnupg state=present

# This role adds keys with specific fingerprints.
# We will not get key updates over HTTPS, like google-chrome.repo does.
- name: Our key file matches our list of fingerprints
  shell: ./keyfile_to_fingerprints.sh linux_signing_key.pub |
         diff -u key_fingerprints.txt /dev/stdin
  args:
    chdir: /ansible-managed/google-chrome/
  changed_when: False
  always_run: True

- name: Supported OS - must use apt or dnf (or possibly yum)
  assert:
    that: ansible_pkg_mgr in ['apt', 'dnf', 'yum']
    msg: This role only supports OS'es based directly on "Debian" or "RedHat".
         See also `ansible -m setup ... | grep ansible_os_family`.

- include: setup-apt-source.yml
  when: ansible_pkg_mgr == 'apt'

- include: setup-yum-repo.yml
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: Install Google Chrome
  package:
    name: google-chrome-stable
    state: present

