- name: RedHat - You need to delete any previous google-chrome.repo
  command: test ! -e /etc/yum.repos.d/google-chrome.repo
  changed_when: False
  always_run: True

- name: RedHat - Disable creation of google-chrome.repo when package is installed
  #
  # Otherwise the package would try to e.g. reset the baseurl.
  # "If you donâ€™t want Google's repository, do
  # `sudo touch /etc/default/google-chrome` before installing the package."
  copy:
    dest: /etc/default/google-chrome
    content: ''

# If we create google-chrome.repo ourself, the package wants to reset baseurl.
# Whereas if google-chrome.repo does not exist, it is considered to be deleted
# or otherwise disabled by user action.  It will not be recreated.  So we can
# set up our own local-google-chrome.repo.
#
- name: RedHat - Add Google Chrome repository
  template:
    src: local-google-chrome.repo.j2
    dest: /etc/yum.repos.d/local-google-chrome.repo
  register: repo

# This test may be slow, only bother when changed.
# (In which case, the next use of dnf would probably have had to do this anyway).
- name: RedHat - Test "dnf check-update"
  when: repo.changed
  command: dnf \
           --disablerepo="*" --enablerepo=local-google-chrome
           check-update
  register: dnf_check_update
  # exit status is 0 on success, 100 if updates available (otherwise 100)
  failed_when: dnf_check_update.rc not in [0, 100]
  args:
    warn: no  # can't use ansible dnf module, it does not implement this
